apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: flowin
spec:
  selector:
    app: reservation-service
  ports:
    - port: 8400
      targetPort: 8400
  type: ClusterIP