apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: infra-account
spec:
  selector:
    app: account-service
  ports:
    - port: 8100       # [수정] Nginx가 8000번으로 들어옴
      targetPort: 8100 # [수정] 컨테이너의 8000번으로 연결
  type: ClusterIP