apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: infra-gateway
spec:
  selector:
    app: nginx-proxy-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: admin
      port: 81
      targetPort: 81
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer