apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: flowin
spec:
  selector:
    app: ai-service
  ports:
    - port: 8500       # [수정] Nginx가 8000번으로 들어옴
      targetPort: 8000 # [수정] 컨테이너의 8000번으로 연결
  type: ClusterIP