apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: flowin
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: plaintext

    - port: 9091
      targetPort: 9091
      name: controller

  type: ClusterIP