apiVersion: v1
kind: Service
metadata:
  name: performance-service
  namespace: flowin
spec:
  selector:
    app: performance-service
  ports:
    - port: 8200
      targetPort: 8200
  type: ClusterIP